- package-lock.json
- package.json
- src/app/layout.tsx
- src/lib/error.ts
- src/lib/get-query-client.tsx
- src/lib/responsive-toaster.tsx
- src/utils/handle-mutation-error.ts
- tailwind.config.ts
- react-hot-toast 설치 및 api 에러 토스트 핸들러 추가
- 수정/삭제 요청 작업 결과를 사용자가 확인할 수 있는 피드백을 제공하기 위해 mutation 실패 시 자동으로 에러 메시지를 토스트 메시지로 띄우는 로직을 추가했습니다.
- react-hot-toast 설치
- 토스트 메시지 위치를 화면 크기(데스크탑, 태블릿, 모바일)에 따라 다르게 적용하는 `ResponsiveToaster` 컴포넌트 작성
- tanstack-query의 mutation 에러 발생 시 토스트 메시지 띄울 수 있도록 queryClient 옵션 설정
[Desktop]
https://github.com/user-attachments/assets/1793feb6-c80e-40fe-9d72-4e88a565edbc
[tablet]
https://github.com/user-attachments/assets/ec31d80b-f557-4c38-8072-29231150c5f8
[mobile]
https://github.com/user-attachments/assets/90a14053-3abf-47cd-8ba1-917bdb1c70ee
영상에서 보이는 목표 삭제 동작은 해당 PR에 포함되어 있지 않습니다. 이 부분은 따로 PR 올릴 예정입니다.
혹시 궁금한 점 있으시면 코멘트 남겨주세요!
close: #170
> [Dev 119] react-hot-toast 설치 및 api 에러 토스트 핸들러 추가

- babel.config.js
- next.config.mjs
- src/app/api/v1/todos/[id]/route.ts
- src/app/api/v1/todos/generate-random-todos.ts
- src/app/api/v1/todos/route.ts
- src/components/dashboard/recently-todo/recently-todo-list.tsx
- src/components/tab-side-menu/tab-side-menu.tsx
- src/services/auth/token.ts
- 배포할 때 생기는 에러를 해결하기 위한 작업
- sentry invalid token error로 인해 sentry 설정 제거
- next/font 에러로 인한 babel 제거
- 타입에러 해결
- (추가) force-dynamic 추가하여 항상 SSR로 동작하도록 구현
close: #189
> [DEV-123] 배포하기 위한 빌드 에러 해결

- src/app/api/v1/goals/[goalId]/route.ts
main 배포를 성공하기 위해서 수정한 내용 한 번씩 확인해주세요
(route 에서는 GET,POST,PUT,DELETE 등 api에 대한 내용만 export 해야해서 수정했습니다.)
> fix: route에 불필요한 export 계정

- src/components/landing-page/landing-header.tsx
- src/components/landing-page/landing-section-1.tsx
- src/components/landing-page/landing-section-7.tsx
- 코드 포맷팅 수정
- 랜딩페이지에서 사용되는 컴포넌트에서 prettier/eslint 규칙에 어긋나는 코드들이 있어 빌드가 실패되었습니다. 이를 해결하기 위해 코드 스타일을 수정했습니다.
#203
> style: 코드 포맷팅 수정

- src/app/(main)/goals/[goalId]/page.tsx
- 목표 상세 페이지 반응형 스타일링 수정
- 목표 상세 페이지의 전체 컨테이너 사이즈가 브레이크 포인트에 따라 특정한 사이즈로 지정되어있어 두 브레이크 포인트 사이의 너비를 가진 디바이스에서는 배치가 어색해보이는 문제가 있었고, 이를 해결하기 위해 클래스를 수정했습니다.
- 브레이크 포인트에 따른 특정 사이즈 지정 클래스 제거
- 일정한 좌우 패딩을 주는 방식으로 수정
[수정 전]
https://github.com/user-attachments/assets/6c0fe296-6aaa-4706-a23d-9969ea9264ec
[수정 후]
https://github.com/user-attachments/assets/2a4a5526-392e-42fd-9011-19cd55a4f6d3
close: #221
> [DEV 134] 목표 상세 페이지 반응형 스타일링 수정

- src/components/tab-side-menu/goals-list.tsx
- src/components/todo/all-list-todo.tsx
- 린트 에러 발생 부분 수정
- 빌드 성공 확인했습니다.
> fix: 빌드 에러 수정

- src/lib/responsive-toaster.tsx
- src/utils/handle-mutation-error.ts
- 토스트 메시지 스타일링 추가
- 토스트 메시지 디자인 적용
- 반응형 사이즈에 따라 상단 기준 offset 값 추가
현재 `tailwind`로 스타일링하는 코드가 제대로 동작하지 않아 inline style로 처리했습니다. 이 부분 참고 부탁드립니다.
그리고 토스트 메시지가 뜨는 위치를 피그마 디자인에 맞춰 기본값으로 지정해두었습니다. (모든 경우 상단 중앙, 상단을 기준으로 offset 차등 적용)
토스트 메시지를 띄우기 위해 `route.ts` 일부를 수정하고 녹화한 영상입니다.
실제로 토스트 메시지 동작을 보고 싶으신 경우 코멘트 달아주시거나, 직접 코드를 수정해서 테스트해주시면 좋을 것 같습니다.
https://github.com/user-attachments/assets/da6406e3-8197-4ff4-9e24-544ec7dbcd5d
close: #229
> [DEV 138] 토스트 메시지 스타일링 추가

- src/components/@common/todo.tsx
- src/components/todo/todo-delete-popup.tsx
- src/hooks/query/use-todo.ts
- 할 일 추가/수정/삭제 시 진행률에 반영 안되는 문제 해결
- 할 일 추가/수정/삭제 시 진행률에 반영 안되는 문제 발생 
- [관련 노션 링크](https://www.notion.so/yuuub/1ad963c8b3a780389fb6f23238af5ffc?pvs=4)
- 할일 추가, 수정 성공 시 응답에 `goalId`가 있다면 무효화 함수에 파라미터로 추가
- 할일 삭제 시 `goalId`가 있으면 받아와 무효화하도록 수정
https://github.com/user-attachments/assets/e821f296-37a5-4d96-aad0-b7f42802e892
close: #236
> [Dev 142] 할 일 추가/수정/삭제 시 진행률에 반영 안되는 문제 해결

- src/app/api/v1/auth/logout/route.ts
- src/components/tab-side-menu/user-profile.tsx
- src/services/auth/index.ts
- src/services/endpoint.ts
> [DEV-89] feat: logout 로그아웃 기능 구현

- src/components/tab-side-menu/logo.tsx
- src/components/tab-side-menu/tab-side-menu.tsx
- src/components/tab-side-menu/tab-toggle.tsx
- src/components/tab-side-menu/user-profile.tsx
- 사이드바 열고 닫을 때 스무스하게 움직이도록 애니메이션이 적용됩니다.
- 명세서에서 스무스하게 움직인다는 게 뭔지 모르겠어서 임의로 그냥 했습니다.
- 마음에 안 드시면 말씀해주세요.
https://github.com/user-attachments/assets/4850b5e6-9641-4262-9600-e7333f139cb6
close: #143
> [DEV-106] 네비게이션 애니메이션 구현

- src/components/tab-side-menu/tab-side-menu.tsx
- 데스크탑 환경이면 열림
- 타블렛 모바일 환경이면 닫힘
- 전 PR에서 되어있는 줄 알았는데 안되어 있었습니다.
close: #251
> [DEV-148] fix: 화면 크기에 따른 네비게이션 열림/닫힘 조건문 추가

- src/app/(auth)/layout.tsx
- src/components/auth/login-form.tsx
- src/components/auth/signup-form.tsx
- 로그인/회원가입 페이지 중간발표 피드백 반영
- 로그인/회원가입 페이지 로고 클릭 시 랜딩 페이지로 이동
- 아이디 필드 라벨 이메일로 변경
https://github.com/user-attachments/assets/9786757d-963b-4409-9589-83938de8dbb4
close: #250
> [Dev 147] 로그인/회원가입 페이지 피드백 반영

- babel.config.js
- instrumentation.ts
- jest.config.ts
- jest.setup.ts
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/global-error.tsx
- src/components/@common/sentry-check.test.tsx
- src/components/@common/sentry-check.tsx
원인:
-  is not a module.ts(2306) 에러
해결:
- ts-jest 라이브러리 설치
- jest.config.ts를 아래와 같이 작성
- 오류없이 빌드된 것을 확인
- 센트리, 제스트를 적용하고 빌드하는 과정에서 에러가 나서 제거를 했었습니다.
- 코드 테스트를 하기 위해서 다시 적용할 필요가 있었습니다.
close: #66 #255
> [DEV-150] chore: sentry, jest 빌드 에러 수정

- src/components/dashboard/recently-todo/recently-todo-container.tsx
- src/components/dashboard/recently-todo/recently-todo-list.tsx
- 목표 상세 페이지의 디자인과 통일성을 지키기 위해
- 최근 등록한 할일의 디자인 수정 (gradient, z-index 등)
- 공통 컴포넌트로 만들려는 부분은 시간이 오래 걸릴 것 같아, 시간 여유 있을 때 진행하겠습니다.
close: #262
> [DEV-152] 최근 등록한 할일 디자인 수정

- src/components/goal-detail/goal-title.tsx
- 목표 이름 수정 관련 버그 수정
- 목표 이름 수정 시 실제로 변경사항이 생기지 않았음에도 불구하고 수정 요청이 발생하는 문제가 있었습니다. 불필요한 요청이기에 방지 로직을 추가하였습니다.
- 목표 이름 수정 시 기존 이름과 같을 경우 API 요청 방지 로직 추가
https://github.com/user-attachments/assets/4f75712a-8b64-4a69-ad43-82195e61b52d
close: #276
> [DEV 158] 목표 이름 수정 관련 버그 수정

- src/app/(main)/layout.tsx
- src/components/tab-side-menu/push-notification-setting-button.tsx
- src/components/tab-side-menu/tab-side-menu.tsx
- src/hooks/query/use-setting.ts
- src/services/endpoint.ts
- src/services/push-notification/index.ts
- src/services/push-notification/query.ts
- src/services/query-key.ts
- 거북목 주의보 알림 설정 토글 버튼 및 API 로직 추가
- 거북목 주의보 알림 설정 토글 버튼 컴포넌트 추가
- 알림 설정 조회/변경 API 로직 추가
https://github.com/user-attachments/assets/ea3b03b2-bc8f-4c68-9046-f0ccc96d5233
close: #297
> [Dev 167] 거북목 주의보 알림 설정 토글 버튼 및 API 로직 추가

- .vscode/settings.json
- src/components/note/detail-sheet.tsx
- 노트 시트로 수정하기, 삭제하기가 가능하도록 구현
- 사용자가 노트 편집을 쉽게 할 수 있도록 하려고
- 중복 코드가 있지만, 중복 코드 제거하지 않고, 기능 구현을 우선하였습니다.
https://github.com/user-attachments/assets/d0a16ea1-bb85-4ccd-92a8-93c8d78b2fe2
close: #307
> [DEV-171] 노트 시트 수정하기, 삭제하기 버튼 추가

- src/components/@common/embeded-frame.tsx
- src/components/@common/portal/sheet.tsx
- src/components/note/detail-sheet.tsx
- src/components/note/link-attached.tsx
https://www.notion.so/yuuub/1ba963c8b3a780f7ae72e51b361902cb
https://github.com/user-attachments/assets/cfe02a8e-7010-4135-aadc-e83c483f3e8b
https://github.com/user-attachments/assets/649ec93f-9788-46d8-b155-bd662934a903
close: #316
> [DEV-175] 임베드 관련 버그 수정

- src/components/todo-modal/todo-modal-open-button.tsx
> [DEV-178] fix: 할일 추가 버튼 안 눌리는 버그 수정

- src/components/@common/embeded-frame.tsx
- src/components/todo/all-list-todo.tsx
문제 :
- 작성페이지에서 링크 임베디드를 할 시 
- 사이즈가 정해져 있는 부모 요소가 없어서 
- 임베디드 넓이가 과하게 넓어져있는 오류를 발견
해결 :
- 작성페이지에서 임베디드 할 시의 임베디드 프레임 스타일을 수정하였습니다.
close: #321
> [DEV-177] fix: 작성페이지 임베디드 스타일링 수정
